### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by daryl552007** [bmino/binance-triangle-arbitrage#102]
Hi,

I get the error below when running the script

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/home/binance-triangle-arbitrage/src/main/../../logs/performance.log'
Emitted 'error' event at:
    at SonicBoom.filterBrokenPipe (/home/binance-triangle-arbitrage/node_modules/pino/lib/tools.js:308:12)
    at SonicBoom.emit (events.js:198:13)
    at fs.open (/home/binance-triangle-arbitrage/node_modules/sonic-boom/index.js:25:13)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@5.3.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-07-27T13_51_23_518Z-debug.log
ubuntu@ip-172-31-14-3:/home/binance-triangle-arbitrage$ Emitted 'error' event at:
Emitted 'error' event at:
    at SonicBoom.filterBrokenPipe^[[A^C

**Comment by bmino** [comment]
Permission denied, huh?

Node is attempting to create a log file but does not have permission to access the file system. Ensure that the user running the program has permissions to create directories and files recursively  in the "binance-triangle-arbitrage" directory

Specifically the directory `/home/binance-triangle-arbitrage/logs/` and two log files in that directory:

- execution.log
- performance.log

**Comment by bmino** [comment]
Closing due to inactivity.

If you are still experiencing this issue, reply and we can reopen
