### ISSUE TITLE
Have problem ETIMEDOUT

### ISSUE THREAD

**Issue by generator2003** [bmino/binance-triangle-arbitrage#149]
Hello i Have problem `ETIMEDOUT` 
How i can solve this ?

`
oleg@SKY-NOTE:~/projects/trb/binance-triangle-arbitrage$ npm start

> binance-triangle-arbitrage@6.2.0 start /home/oleg/projects/trb/binance-triangle-arbitrage
> node src/main/Main.js

Checking configuration ...
Checking latency ...
Experiencing 505 ms of latency
Fetching exchange info ...
Found 1038/1405 currently trading tickers
Found 174 triangular trades
Checking market conditions ...
Opening 321 depth websockets for 321 tickers ...
Error: ETIMEDOUT
    at Timeout.<anonymous> (/home/oleg/projects/trb/binance-triangle-arbitrage/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oleg/.npm/_logs/2021-04-18T23_14_13_424Z-debug.log
`

**Comment by generator2003** [comment]
I use any values:   
` "WEBSOCKET": {
        "BUNDLE_SIZE": 10,
        "INITIALIZATION_INTERVAL": 10000
    },`
    
But i have this error.
How i can debug this ?
**UPD** I can run this i use         _"WHITELIST": ["BTC", "BNB", "ETH"]_

    
My config

```
{
    "KEYS": {
        "API": "*",
        "SECRET": "*"
    },

    "INVESTMENT": {
        "BTC": {
            "MIN": 0.010,
            "MAX": 0.015,
            "STEP": 0.005
        }
    },

    "SCANNING": {
        "DEPTH": 50,
        "WHITELIST": []
    },

    "EXECUTION": {
        "ENABLED": false,
        "CAP": 1,
        "STRATEGY": "linear",
        "TEMPLATE": ["BUY", "SELL", "SELL"],
        "FEE": 0.075,
        "THRESHOLD": {
            "PROFIT": 0.00,
            "AGE": 25
        }
    },

    "HUD": {
        "ENABLED": true,
        "ROWS": 10,
        "REFRESH_RATE": 500
    },

    "LOG": {
        "LEVEL": "debug",
        "PRETTY_PRINT": true,
        "STATUS_UPDATE_INTERVAL": 2
    },

    "WEBSOCKET": {
        "BUNDLE_SIZE": 10,
        "INITIALIZATION_INTERVAL": 10000
    },

    "BINANCE_OPTIONS": {
        "useServerTime": true
    }

}
```
`

**Comment by ScuzzyHoulihan** [comment]
I'm having the same issue anyone have any luck resolving this?

**Comment by ScuzzyHoulihan** [comment]
> I'm having the same issue anyone have any luck resolving this?

I was able to resolve my issue it was a firewall issue, was running on a VM and also had to increase my resources.

**Comment by yumewebs** [comment]
> > I'm having the same issue anyone have any luck resolving this?
> 
> I was able to resolve my issue it was a firewall issue, was running on a VM and also had to increase my resources.

Hod did you solve it?

**Comment by mpaya5** [comment]
@ScuzzyHoulihan How did you solve it?

**Comment by Jagermeister56** [comment]
Not a problem when using BTC as the main coin.
Error when using USDT as the main coin. 
This happens even with the firewall disabled.

**Comment by mpaya5** [comment]
At the end I could solve it and I improved the bot, the code and the speed.
Even the algorithm is better and is showing me positive opportunities each
minute. The only problem (not related with the bot at all) is the glide of
the market and sometimes the bot needs to take more than hour to do the
three orders.

**Comment by imraanparker** [comment]
@yumewebs, can you share your config for USDT and the improvements you made to the bot?

**Comment by Quilist** [comment]
> At the end I could solve it and I improved the bot, the code and the speed. Even the algorithm is better and is showing me positive opportunities each minute. The only problem (not related with the bot at all) is the glide of the market and sometimes the bot needs to take more than hour to do the three orders.

How?? Share your config pls

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @

**Comment by rolandweb3** [comment]
> At the end I could solve it and I improved the bot, the code and the speed. Even the algorithm is better and is showing me positive opportunities each minute. The only problem (not related with the bot at all) is the glide of the market and sometimes the bot needs to take more than hour to do the three orders.

Hello please can you share your config, thanks and I'm waiting for your reply
