### ISSUE TITLE
Error when npm start

### ISSUE THREAD

**Issue by trdhiepitvnu** [bmino/binance-triangle-arbitrage#16]
Hi,

I use Mac
nmp 6.4.1
node 10.5.0

I run npm install ==> OK
But, when I run npm start ==> Error

Querying exchangeInfo
TypeError: Cannot read property 'indexOf' of undefined
    at /Users/admin/Documents/Binance/binance-triangle-arbitrage-3.5.2/src/main/Main.js:25:75
    at Array.forEach (<anonymous>)
    at BinanceApi.exchangeInfo.then (/Users/admin/Documents/Binance/binance-triangle-arbitrage-3.5.2/src/main/Main.js:22:22)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

Could you help me fix this bug?

**Comment by bmino** [comment]
Thanks for pointing this out! I have delivered the fix.
Please confirm this works for you, @trdhiepitvnu  :)
