### ISSUE TITLE
npm start throws an error

### ISSUE THREAD

**Issue by nanomago** [bmino/binance-triangle-arbitrage#167]
I tried it in:
- MacOS 11.3.1
- NodeJS 14.15.4
- Npm 6.14.10
[error.log](https://github.com/bmino/binance-triangle-arbitrage/files/6570543/error.log)

SyntaxError: /Users/XXXXXXXXX/Documents/Binance triangle arbitrage/binance-triangle-arbitrage-master/config/config.json: Unexpected string in JSON at position 793
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/nanomago/Documents/Binance triangle arbitrage/binance-triangle-arbitrage-master/src/main/Main.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/XXXXXXXXX/.npm/_logs/2021-05-31T13_22_57_074Z-debug.log

**Comment by bmino** [comment]
Hey, looks like you have an invalid config.json file. Post your `config/config.json` file (without any keys) if you would like to debug the issue

**Comment by nanomago** [comment]
Thanks a lot, bmino. When you told me the problem should be in the config.json file I compared it with the .example file and detected the error, now it's working.

I tried:
    "LOG": {
        "LEVEL": "debug", "info",
instead of:
    "LOG": {
        "LEVEL": "debug",

but it didn't work. Now it's working, as I reverted the change, but, may I ask how to add "info"?

Thanks in advanced

**Comment by bmino** [comment]
LOG.LEVEL can only have one log level string value. They are a hierarchy so using "info" will also include everything lower like debug, warn, fatal, etc.

**Comment by nanomago** [comment]
Thanks for your explanation, @bmino, understood.

The bot is working perfectly, by the way. Thanks again.

**Comment by bmino** [comment]
excellent! cool gonna close this as resolved then
