### ISSUE TITLE
Minimum investment quantity (INVESTMENT.BASE.MIN) must be a positive number

### ISSUE THREAD

**Issue by dethie** [bmino/binance-triangle-arbitrage#168]
I am trying to run this on a google cloud but I keep getting this error.

I am running this on a windows and it is running no problem but on a ubuntu 20.04 LTS seems to be coming up with this
```
WARNING! Order execution is enabled!
Checking configuration ...
/home/-/bot/src/main/Validation.js:38
                throw new Error(msg);
                ^
Error: Minimum investment quantity (INVESTMENT.BASE.MIN) must be a positive number
    at Object.keys.forEach.BASE (/home/-/bot/src/main/Validation.js:38:23)
    at Array.forEach (<anonymous>)
    at Object.configuration (/home/-/bot/src/main/Validation.js:19:40)
    at Object.<anonymous> (/home/-/bot/src/main/Main.js:26:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/-/.npm/_logs/2021-07-03T15_19_36_699Z-debug.log
```

`"INVESTMENT": {
        "BASE": "USDT",
        "MIN": 15,
        "MAX": 50,
        "STEP": 0.005
    },`

**Comment by bmino** [comment]
Please review the config readme file for usage of configuration. It appears you are using an outdated config format

**Comment by dethie** [comment]
Your a gem!! I was racking my brain what the issue was xD
