### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by karanmahal47** [bmino/binance-triangle-arbitrage#169]
Hey,

I've been running into a module not found error, how do i go about fixing it?

> binance-triangle-arbitrage@6.2.0 start /Users/Manny/binance-triangle-arbitrage
> node src/main/Main.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../../config/config'
Require stack:
- /Users/Manny/binance-triangle-arbitrage/src/main/Main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/Manny/binance-triangle-arbitrage/src/main/Main.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/Manny/binance-triangle-arbitrage/src/main/Main.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Manny/.npm/_logs/2021-07-14T20_03_44_320Z-debug.log

**Comment by bmino** [comment]
Hey! I'd recommend you read the project [README](https://github.com/bmino/binance-triangle-arbitrage) first to get a feel for what is required to setup the project initially. You are missing the config file as described here:

![image](https://user-images.githubusercontent.com/10902767/125825597-00ad72b1-5256-43db-888a-b8ca399d034d.png)
