### ISSUE TITLE
Error when npm start.  Error: Cannot find module '../../config/live.config'

### ISSUE THREAD

**Issue by YuriyTigiev** [bmino/binance-triangle-arbitrage#19]
(peregrine) ytigiev@instance-1:~/binance-triangle-arbitrage$ npm start

> binance-triangle-arbitrage@3.5.2 start /home/ytigiev/binance-triangle-arbitrage
> node src/main/Main.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../config/live.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ytigiev/binance-triangle-arbitrage/src/main/ArbDisplay.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@3.5.2 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@3.5.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ytigiev/.npm/_logs/2019-01-05T17_03_14_193Z-debug.log
(peregrine) ytigiev@instance-1:~/binance-triangle-arbitrage$

**Comment by bmino** [comment]
Hi! Did you follow the Readme instruction section titled "Configuration?" It looks like you are missing that step

**Comment by YuriyTigiev** [comment]
You are right. But create default configuration without an extension .example.

**Comment by YuriyTigiev** [comment]
Ok. Understand
