### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mahyarx** [bmino/binance-triangle-arbitrage#49]
hello i got this error after "npm start"

WARNING! Order execution is enabled!

Successfully pinged the Binance api in 593 ms
Found 461/502 currently trading tickers
TypeError: Cannot read property '0' of undefined
    at Object.createTrade (PATH\src\main\MarketCache.js:66:46)
    at MarketCache.symbols.forEach.symbol3 (PATH\src\main\MarketCache.js:56:43)
    at Set.forEach (<anonymous>)
    at MarketCache.symbols.forEach.symbol2 (PATH\src\main\MarketCache.js:55:33)
    at Set.forEach (<anonymous>)
    at Object.getTradesFromSymbol (PATH\src\main\MarketCache.js:54:29)
    at Object.initialize (PATH\src\main\MarketCache.js:31:49)
    at ArbitrageExecution.refreshBalances.then.then.then.then.exchangeInfo (PATH\src\main\Main.js:24:39)
    at <anonymous>
    a

**Comment by Memoi** [comment]
Hi, did you copy/paste your old config file on the folder config of the new release ?
They are different

**Comment by mahyarx** [comment]
yes, exactly that was the issue, thank you, replaced new config and everything works well now

**Comment by bmino** [comment]
Thanks @Memoi!

Go ahead and close this issue, @mahyarx, if you are no longer experiencing it
