### ISSUE TITLE
Error SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by Atabani** [bmino/binance-triangle-arbitrage#56]
hello, the application runs for a while and then terminates with the following message, is there something wrong with binance or the application?
```

Successfully pinged the Binance api in 506 ms
Found 473/519 currently trading tickers
Found 222 triangular relationships
Checking configuration ...
Checking balances ...
Opening 473 depth websockets ...

Execution Strategy:     linear
Optimization Ticks:     4 ticks(s)
Execution Limit:        1 execution(s)
Profit Threshold:       0.30%
Age Threshold:          300 ms
Log Level:              info

undefined:3
return typeof s === "string" ? %FlattenString(s) : s
                               ^

SyntaxError: Unexpected token %
    at Pino.write (/root/binance-triangle-arbitrage/node_modules/pino/lib/proto.js:137:21)
    at Pino.LOG [as info] (/root/binance-triangle-arbitrage/node_modules/pino/lib/tools.js:35:26)
    at Timeout.calculateArbitrage [as _onTimeout] (/root/binance-triangle-arbitrage/src/main/Main.js:79:43)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@5.1.1 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-15T20_57_06_372Z-debug.log

```

**Comment by Atabani** [comment]
The content of 2019-05-15T20_57_06_372Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v12.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle binance-triangle-arbitrage@5.1.1~prestart: binance-triangle-arbitrage@5.1.1
6 info lifecycle binance-triangle-arbitrage@5.1.1~start: binance-triangle-arbitrage@5.1.1
7 verbose lifecycle binance-triangle-arbitrage@5.1.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle binance-triangle-arbitrage@5.1.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/$
9 verbose lifecycle binance-triangle-arbitrage@5.1.1~start: CWD: /root/binance-triangle-arbitrage
10 silly lifecycle binance-triangle-arbitrage@5.1.1~start: Args: [ '-c', 'node src/main/Main.js' ]
11 silly lifecycle binance-triangle-arbitrage@5.1.1~start: Returned: code: 1  signal: null
12 info lifecycle binance-triangle-arbitrage@5.1.1~start: Failed to exec start script
13 verbose stack Error: binance-triangle-arbitrage@5.1.1 start: `node src/main/Main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
14 verbose pkgid binance-triangle-arbitrage@5.1.1
15 verbose cwd /root/binance-triangle-arbitrage
16 verbose Linux 5.0.0-13-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.2.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error binance-triangle-arbitrage@5.1.1 start: `node src/main/Main.js`
22 error Exit status 1
23 error Failed at the binance-triangle-arbitrage@5.1.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bmino** [comment]
This appears to be an issue with pino (which handles logging). I haven't encountered this before

You have updated your dependencies (via `npm install`) right?

**Comment by Atabani** [comment]
Yes I did ```
npm install
``` before running ```
npm start
``` is there any other command that I need to do ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
