### ISSUE TITLE
I get this whenever I ]$ npm run live

### ISSUE THREAD

**Issue by tsrnc2** [bmino/binance-triangle-arbitrage#7]
/home/jacob/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1749
                            if (err) throw err;
                                     ^

Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/jacob/binance-triangle-arbitrage/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@3.4.0 live: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@3.4.0 live script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacob/.npm/_logs/2018-07-21T03_44_46_226Z-debug.log

**Comment by bmino** [comment]
Did you update the project dependencies with the following?
```
npm install
```

**Comment by tsrnc2** [comment]
I was able to get it to run by setting DEPTH_SIZE: 10. so closing.
